### ISSUE TITLE
Suggestion for feature

### ISSUE THREAD

**Issue by 2braincells2go** [ssokurenko/jquery-mobile-password-generator#1]
Very nice password generator!

Not sure it can be accomplished but if you could implement either:

http://www.lettersmarket.com/view_blog/a-3-copy_to_clipboard_lmcbutton.html

or

http://lettersmarket.com/lmcbutton.html

Would be killer.

Attempted it myself but the app.js and input field in index is over my head.

Any ideas how to make it simple? Really like to use the app for classroom project.

Cheers!

**Comment by ssokurenko** [comment]
Thanks @2braincells2go !
Will consider the feature implementation.

**Comment by 2braincells2go** [comment]
Thanks. Many users have no clue how to copy the generated password and having a "copy" button would solve.

**Comment by 2braincells2go** [comment]
I might add that clipboard.js might be another option:

https://github.com/zenorocha/clipboard.js

For life of me cannot get any of the methods to work. Hoping you will find time to help us.

Cheers!

**Comment by ssokurenko** [comment]
Hi @2braincells2go ,
Simple feature of copying to clipboard implemented: https://github.com/ssokurenko/jquery-mobile-password-generator/commit/9a6ee4eda32933c162f2056f86df385c7a0d295d

Note, that the feature itself is not supported on some browsers because of security restrictions.

Test results:
- Desktop Chrome  46.0.2490.86 (Mac OS X): _works_
- Mobile Safari (iOS 9.0): _doesn't work_

**Comment by 2braincells2go** [comment]
Thank you, that was very nice of you to do. Will make it much easier for some younger users to use.

Cheers!

**Comment by 2braincells2go** [comment]
One other quick question please: is there any easy way to disable the popup alert when password is copied?

No real issue, just wondering if possible.

Thanks again for the mod.

EDIT: Pretty sure found a way using:

alert = function() {};

Also found info for Chrome and other browsers using console.log:

window.alert = function ( text ) { console.log( 'tried to alert: ' + text ); return true; };
alert( new Date() );

Will play around with next week and see what happens.

Cheers!

**Comment by ssokurenko** [comment]
Hi @2braincells2go, yes, nice that you've found it out.
You sould comment the alert: https://github.com/ssokurenko/jquery-mobile-password-generator/blob/gh-pages/js/app.js#L93

Also find and comment it in the compressed file: https://github.com/ssokurenko/jquery-mobile-password-generator/blob/gh-pages/js/app.min.js

Cheers
